export const GET_DATA_MASTER = 'GET_DATA_MASTER';
export const GET_EXPAND = 'GET_EXPAND';
export const GET_DETAIL_CURRICULUM = 'GET_DETAIL_CURRICULUM';
export const GET_DATA_MASTER_NATIVE = 'GET_DATA_MASTER_NATIVE';
export const GET_DATA_MASTER_JAVA = 'GET_DATA_MASTER_JAVA';